### PR TITLE
Return empty array on empty collection response

### LINKED ISSUE #46: Requesting an empty collection returns an object of the return type
When requesting a collection that returns an empty result the result is actually parsed to an object that was given in the ReturnType.

Example:

```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(microsoft.graph.plannerPlan)",
    "@odata.count": 0,
    "value": []
}
```

Results in

```
object(Microsoft\Graph\Model\PlannerPlan)[400]
  protected '_propDict' => 
    array (size=3)
      '@odata.context' => string 'https://graph.microsoft.com/v1.0/$metadata#Collection(microsoft.graph.plannerPlan)' (length=82)
      '@odata.count' => int 0
      'value' => 
        array (size=0)
          empty
```

I think the system should handle this as an empty array. The problem can be found in the class \Microsoft\Graph\Http\GraphResponse - method getResponseAsObject - line 152 where the system checks if the variable '$values' is available. When given an empty array the system returns false and continues to parse the collection as an object, returning false results.

### PR DESCRIPTION
**Pull request by guilliamxavier**
Fixes #46
Closes #105

### CODE REVIEW

**Comment by guilliamxavier** [comment]
(I have added 2 extra commits I think make the code better, but they're optional, feel free to discard them)

**Comment by MIchaelMainer** [comment]
Thank you @guilliamxavier . I'm going to run this tomorrow. I'll be bumping the version to 2.0.0 as it is possible that people have taken a dependency on the old behavior.

**Comment by guilliamxavier** [comment]
Thank you for responding. As concerns a hypothetical dependency on the buggy behavior... given for example

```php
$query = http_build_query(['$filter' => $filter, '$orderby' => $orderby]);
$userGrabber = $graph->createCollectionRequest('GET', "/users?$query")
                     ->setReturnType(Model\User::class)
                     ->setPageSize(100);
$users = $userGrabber->getPage();
```

I admit that (although very unlikely) there is indeed a *slight possibility* that someone might have written some "fragile" code like

```php
// this code assumes that $users cannot be empty:
if (is_array($users)) {
    /* code that must be run if the real collection was not empty (use $users) */
} else {
    /* code that must be run if the real collection was empty (don't use $users) */
}
```

and would need to change it (actually, to *fix* it), but there's a *much higher probability* that people have written reasonable code like

```php
// this code trusts that $users is an array:
if (count($users) > 0) {
    /* code that must be run if the real collection was not empty (use $users) */
} else {
    /* code that must be run if the real collection was empty (don't use $users) */
}
```

then if got bitten by the bug (e.g. "expected array, got object"), adapted it like this:

```php
// this code checks to be sure that $users is an array:
if (is_array($users) && count($users) > 0) {
    /* code that WILL be run if the real collection was not empty (use $users) */
} else {
    /* code that WILL be run if the real collection was empty (don't use $users) */
}
```

or (that's me) like that:

```php
// Workaround for bug https://github.com/microsoftgraph/msgraph-sdk-php/issues/46
if (!is_array($users)) {
    $users = [];
}

// this code can now be confident that $users is an array:
if (count($users) > 0) {
    /* code that WILL be run if the real collection was not empty (use $users) */
} else {
    /* code that WILL be run if the real collection was empty (don't use $users) */
}
```

For me it would be a bit sad if people who are using version `^1.0` / `1.*` would not get the *bugfix* (until --if ever-- they do a *major* version upgrade to `^2.0` / `2.*`) because of an unknown [small] number of "sloppy" coders... But if you have a very strict BC policy (even for bugs), I guess that's how it is... Anyhow thank you for considering 🙂

**Comment by guilliamxavier** [comment]
I see that this was released in 1.13.0 (with a bump to PHP 7.1) 🎉 Thanks

**Pull request merged**
