### PR TITLE
#Fix: Add backslash to class reference for classes outside current namespace (BETA).

### LINKED ISSUE #424: Fix calling of classes from different namespace
Currently all `getXXX()` methods that make calls to class in other namespaces in the SDK fail to resolve the classes due to missing backslash at the beginning of the class instantiation, for instance,

```php
  function getXXX(){
        return new NameSP\ClassName($argument);
   }
``` 
should be
```php
  function getXXX(){
        return new \NameSP\ClassName($argument);
   }
``` 
Sample code with the issue.
https://github.com/microsoftgraph/msgraph-sdk-php/blob/5e4332208618c80b678db614edf25fc0e24e5b4b/src/CallRecords/Model/CallRecord.php#L164 
[AB#8649](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8649)

### PR DESCRIPTION
**Pull request by SilasKenneth**
Currently all `getXXX()` methods that make calls to class in other namespaces in the SDK fail to resolve the classes due to missing backslash at the beginning of the class instantiation, for instance,

```php
  function getXXX(){
        return new Beta\NameSP\ClassName($argument);
   }
``` 
should be
```php
  function getXXX(){
        return new \Beta\NameSP\ClassName($argument);
   }
``` 

#### What this PR does?
 - Fixes an issue mentioned in PR #412 (Add `\` to namespaces outside the current namespace.
 - This PR fixes the issue for `beta` models.
 
 ##### Screenshots
 
Screenshot 2021-03-19 230005

Closes #424 

#### Link to PR on [microsoftgraph/MSGraph-SDK-Code-Generator](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/)
https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/498

### CODE REVIEW

**Review by Ndiritu — APPROVED** [review]
Looks good. Just need to fix a few merge conflicts with `dev`

**Review by MIchaelMainer — APPROVED** [review]

**Comment by MIchaelMainer** [comment]
Make sure you link to the generator changes that resulted in this change.
https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/498

To get this into main for automation.
https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/501 - into main

**Comment by SilasKenneth** [comment]
> Make sure you link to the generator changes that resulted in this change.
> [microsoftgraph/MSGraph-SDK-Code-Generator#498](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/498)
> 
> To get this into main for automation.
> [microsoftgraph/MSGraph-SDK-Code-Generator#501](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/501) - into main

Added the link

**Comment by MIchaelMainer** [comment]
There was an update to the beta metadata, and we just pulled in changes based on that. At this point, I suggest that you rerun your changes against the latest metadata and merge into the latest version on the PHP repo. 

https://github.com/microsoftgraph/msgraph-sdk-php/pull/428

**Comment by SilasKenneth** [comment]
Closing in favor of #431. Metadata for code generation has since been updated

**Pull request closed without merging**
