### PR TITLE
add @throws to docblocks

### PR DESCRIPTION
**Pull request by iPoul**
Updated docblocks to contain @throws

### CODE REVIEW

**Comment by MIchaelMainer** [comment]
@iPoul Thank you for the pull request! We really appreciate it! 

We won't be able to take your pull request as is. The @throws docblocks in the /models/* accessors are incorrect as the model calls should not result in a GraphException.   Your changes in Enum.php, Graph.php, and GraphCollectionRequest.php are helpful and we can take those. 

Plus, your brought to my attention that we are emitting too much whitespace. I opened something on that in my backlog. 910034

**Comment by iPoul** [comment]
@Michael Thanks for getting back on the PR, i will fix the models tomorrow morning, different timezone and all, heading to bed for now. 👍

**Comment by MIchaelMainer** [comment]
@iPoul Goodnight to you. 

We generate the models so all changes in models we have to apply via C# + T4 templates metaprogramming for PHP code files.  The fun happens here:

https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/tree/dev/Templates/PHP/Model

**Comment by iPoul** [comment]
@MIchaelMainer Thanks,

I reverted the model changes anyhow, but i will look into the T4.

**Pull request closed without merging**
