### PR TITLE
Updated models

### PR DESCRIPTION
**Pull request by krizalys**
Updated models after having fixed the PHP model template for complex types.

See https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/220.

### CODE REVIEW

**Comment by krizalys** [comment]
@MIchaelMainer What do you think about this?

**Comment by krizalys** [comment]
@MIchaelMainer @muthurathinam What do you think about this?

**Comment by MIchaelMainer** [comment]
@krizalys Thank you for taking the time to open the PR on both the generator and the generated files. 

I'm not too familiar with PHP syntax so I want to verify my understanding. 

The way we currently have it setup in generation, we are generating a condition that will always be false because `Microsoft\Graph\Model\\DateTime` and `Microsoft\Graph\Model\\GuzzleHttp\Psr7\Stream` do not exist so we always create and return a new DateTime or a StreamInterface. Is this correct?

Do we need the preceding `\` for the type name? For example, `"\DateTime"` versus `"DateTime"`.

Also, should we be using single quotes instead of double quotes since double quotes is useful for variable interpolation, which we aren't doing?

**Comment by krizalys** [comment]
@darrelmiller @MIchaelMainer Thanks for the feedback. Looking forward for having this fix applied. Kindly let me know what you need from me.

**Comment by SilasKenneth** [comment]
@krizalys closing this since the issue has so far been fixed. Thanks for the contribution.

**Pull request closed without merging**
