### PR TITLE
Remove default assignment of code generation PRs

### PR DESCRIPTION
**Pull request by Ndiritu**
It's now possible to trigger pr-validation steps for code generation PRs by manually assigning yourself the PR.
Removing the default assignment allows Kenneth & I to manually assign ourselves the PRs to trigger the validation steps instead of un-assigning ourselves first.

Reverts change made in #466

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoftgraph/msgraph-sdk-php/pull/482)

### CODE REVIEW

**Comment by MIchaelMainer** [comment]
Why do we want this?

**Comment by Ndiritu** [comment]
Our hack to make pr-validation steps run for code-gen PRs is to manually assign ourselves the PR. The assignment action triggers the steps. If we're already assigned by default (change earlier made in #466 ), I have to un-assign myself then assign myself again to trigger the steps. Thought it would be easier to not assign by default and allow any of us to assign ourselves to trigger the steps.

**Comment by MIchaelMainer** [comment]
This change will add more time to code reviews. 

In that case, to validate a PR, we have to assign ourselves before it runs. As we add more validation, it will take more time, and you will have to wait longer before a PR is ready to review. The validation step is part of the review. Perhaps this is not a thing for manual created PRs, but for generated PRs, it does add time. 

As it is currently, generated PRs are ready for review most of the time as the automatic validation steps have already ran by the time we get to the PR.

**Comment by Ndiritu** [comment]
I agree that this could increase time for code reviews.

Without any intervention the generated PRs don't run validation steps.

We can chat more at standup.

**Comment by MIchaelMainer** [comment]
Got it. I must not understand something. We do get test runs with this Azure Pipeline;

https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/dev/.azure-pipelines/generation-templates/php-run-tests.yml

**Review by MIchaelMainer — APPROVED** [review]
We should consider using an Azure Pipeline to automatically validate the PR to work around the issue where GitHub actions won't kickoff automatically when using the GH token.

**Pull request merged**
